### PR TITLE
Updated validation example

### PR DESCRIPTION
**Pull request by MarkPflug**
Here is an example of using the `DbDataReader.Validate` API. I think it captures most of the questions you have. If you have any suggestions on how the API can be improved, I'd appreciate hearing your thoughts. This API is still "preview", because I'm not sure I'm happy with it yet. Seeing your use-case has been useful. I'm going to close the issue in my repo. Let's continue the discussion here.

### CODE REVIEW

**Comment by sherman89** [comment]
@MarkPflug Thank you for this example! I tried it out here quickly and noticed that while the validation works, the data is not fetched and stored anywhere.

Calling `GetRecords` would advance the reader and break validation. do I have to then read the data cell by cell manually? I could of course read through the excel another time just to read but of course that's less optimal, and reading cell by cell means I would have to check for type and get by ordinal which is fine but if I can avoid all the manual work that would lead to cleaner code 😄 

Ideally would be nice to call `GetRecords` then while it reads each cell, an event like `OnCellRead` or something is invoked that would allow me to validate the value, then when reading the entire row is done there would be an `OnRowRead` event (so I can for example validate 2 cells together in the row) and then finally `OnColumnRead` or `OnRecordRead` that would allow me to validate vertically for something like duplicate id's.

What are your thoughts on this? Is it bad library design?

Thank you very much!

**Comment by MarkPflug** [comment]
I've modified the PR to include schema mapping and record binding. I think this handles what you were looking for?

**Comment by sherman89** [comment]
Yes it does, thank you very much! 😄 I will continue my tests with the latest version. Very much appreciate your help!

**Comment by MarkPflug** [comment]
It was useful to see how you're trying to use my libraries, so thanks for sharing your experience/struggles.

**Comment by sherman89** [comment]
I'm happy to give feedback 👍 Looking forward to improvements and updates!

I've merged the PR and will refactor it to my liking. If anything comes up I'll let you know here. 

Thanks again!

**Comment by sherman89** [comment]
@MarkPflug How do I reproduce a "schema error"? I'd like to see something return from `DataValidationContext`'s `GetErrors`?

The same is also called before validating Id columns:
```csharp
if (context.IsValid(_idOrd))
{
    var id = context.GetValue<int>(_idOrd);
    if (!_seenIds.Add(id))
    {
        // already seen it
        Console.WriteLine($"Duplicate Id at row {dr.RowNumber} col {_idOrd} value '{id}'.");
    }
}
```

I tried breaking the schema with invalid field names and types but I wasn't able to get errors from that method.

Thanks!

**Comment by sherman89** [comment]
I pushed some refactoring and improvement changes to master, I haven't yet added those special validations (GetOrdinal etc...) but so far looks quite good. I think tomorrow I will do those and start to implement the real feature in our ASP.NET app.

This looks a lot cleaner and simper than what I had. Thank you!

Some documenation and real world examples would probably help people adopt this a lot faster, but I understand maybe you want to still think about things like validation, although I think it works pretty good actually. If I come up with any ideas I'll make sure to let you know, cheers!

**Pull request merged**
